### ISSUE TITLE
Quitar fondo y recortar bien las siguientes imágenes

### ISSUE THREAD

**Issue by jdlmd** [jdlmd/Combate_pokemon#10]
![Relleno](https://user-images.githubusercontent.com/82572705/115584306-fb692e80-a2ca-11eb-92bf-c104cf569aa1.png)

![barra](https://user-images.githubusercontent.com/82572705/115584395-0cb23b00-a2cb-11eb-8d6a-d8d6be598658.png)

**Comment by jdlmd** [comment]
Esta también, por favor

![Pokeball](https://user-images.githubusercontent.com/82572705/115586041-77b04180-a2cc-11eb-9098-aba54c3bba1c.png)

**Comment by japs18** [comment]
Me pongo a ello ahora mismo

**Comment by nlm18** [comment]
[recorte.zip](https://github.com/jdlmd/Combate_pokemon/files/6352452/recorte.zip)
las dos primeras imagenes recortadas

**Comment by japs18** [comment]
Usad estas mejor
[Recortadas.zip](https://github.com/jdlmd/Combate_pokemon/files/6352543/Recortadas.zip)
