### ISSUE TITLE
Fondo de escenarios

### ISSUE THREAD

**Issue by jdlmd** [jdlmd/Combate_pokemon#11]
Alguno puede recortar bien el fondo de esas imágenes?

[res.zip](https://github.com/jdlmd/Combate_pokemon/files/6364150/res.zip)

**Comment by japs18** [comment]
Lo hago ahora en un momento

**Comment by japs18** [comment]
[fondos.zip](https://github.com/jdlmd/Combate_pokemon/files/6364721/fondos.zip)
Aqui estan
