### ISSUE TITLE
Otro xD

### ISSUE THREAD

**Issue by jdlmd** [jdlmd/Combate_pokemon#12]
![text_box](https://user-images.githubusercontent.com/82572705/115874840-e2848880-a444-11eb-813d-393606cec29d.png)

**Comment by japs18** [comment]
![textBox](https://user-images.githubusercontent.com/82661306/115962450-c9024000-a51b-11eb-8dcd-294286c5bad3.png)

**Comment by jdlmd** [comment]
Perfecto, muchas gracias
