### ISSUE TITLE
Creación de personajes propios para la interfaz gráfica

### ISSUE THREAD

**Issue by nlm18** [jdlmd/Combate_pokemon#8]
El dibujo tendrá que tener gráficos pokemon y que sea diferenciable cada personaje

**Comment by jdlmd** [comment]
Perfecto. A mí me gustaría tenerlo con la camiseta negra

**Comment by nlm18** [comment]
Adjunto los personajes femeninos en formato png
[Personajes femeninos.zip](https://github.com/jdlmd/Combate_pokemon/files/6352369/Personajes.femeninos.zip)

**Comment by nlm18** [comment]
Otro más
[Personaje_Jesus.zip](https://github.com/jdlmd/Combate_pokemon/files/6356587/Personaje_Jesus.zip)

**Comment by nlm18** [comment]
Intento de que se vean mejor en la interfaz
[Personajes.zip](https://github.com/jdlmd/Combate_pokemon/files/6367378/Personajes.zip)

**Comment by nlm18** [comment]
Personajes definitivos
[Definitivo.zip](https://github.com/jdlmd/Combate_pokemon/files/6369678/Definitivo.zip)
